### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by kyleconroy** [lfittl/pg_query_go#28]
We're coming up on a year since the last commit to this repository. Is there any plan to restart development?

**Comment by kyleconroy** [comment]
I take it that's a yes 😿

**Comment by lfittl** [comment]
@kyleconroy No, but development mostly happens on libpg_query (including work to update to Postgres 12 parser, which should be finished soon). Your PRs are certainly welcome, if you have things you would like to see improved on this library specifically.

**Comment by kyleconroy** [comment]
> including work to update to Postgres 12 parser, which should be finished soon

Excellent news! Please let me know if there's anything I can do to help on updating pg_query_go to use the newest version of libpg_query.
