### ISSUE TITLE
can not complie the project with go build

### ISSUE THREAD

**Issue by sfiloveyou** [lfittl/pg_query_go#3]
there is an error with run go build command,and the error msg is below

In file included from include/postgres.h:47,
                 from gopkg/src/github.com/lfittl/pg_query_go/parser/contrib_pgcrypto_sha1.c:50:
include/c.h:298: error：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int128’
include/c.h:299: error：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘uint128’

after i commented c.h:298 and c.h:299 , run go build again ,there is an other errors

gopkg/src/github.com/lfittl/pg_query_go/parser/pg_query_fingerprint.c:98: undefined reference to `_Static_assert'
gopkg/src/github.com/lfittl/pg_query_go/parser/pg_query_fingerprint.c:98: undefined reference to `_Static_assert'
gopkg/src/github.com/lfittl/pg_query_go/parser/pg_query_fingerprint.c:100: undefined reference to `_Static_assert'
gopkg/src/github.com/lfittl/pg_query_go/parser/pg_query_fingerprint.c:100: undefined reference to `_Static_assert'
gopkg/src/github.com/lfittl/pg_query_go/parser/pg_query_fingerprint.c:105: undefined reference to `_Static_assert'
/tmp/go-build140904706/github.com/lfittl/pg_query_go/parser/_obj/pg_query_fingerprint.o:/home/cloud/gopkg/src/github.com/lfittl/pg_query_go/parser/pg_query_fingerprint.c:105: more undefined references to `_Static_assert' follow

**Comment by sfiloveyou** [comment]
my os is centos6.8 and gcc is the default with os.
go version is 1.8

**Comment by lfittl** [comment]
@sfiloveyou Thanks for the report!

I suspect you might have a gcc version thats too old - afaik the way we currently extract the parser, we depend on at least gcc 4.6 (which supports 128 bit integers).

Is there a way for you to upgrade gcc?

**Comment by sfiloveyou** [comment]
thank you lfittl ,i have updated my gcc to 4.8.2 and build the project successful.
