### ISSUE TITLE
Bug: RangeFunctions ColumnDefs not parsed

### ISSUE THREAD

**Issue by avinoamr** [lfittl/pg_query_go#5]
`SELECT * FROM FUNC(...) AS (t int)` <- No ColumnDefs
`SELECT * ROWS FROM (FUNC(...))` <- Syntax error

The returned RangeFunction node is a list of just one element instead of several (because the ROWS syntax fails to parse). That one element is indeed a list of 2 elements as documented:

1. FuncCall node
2. Nil (should be a list of ColumnDefs according to the docs).

Any clue what's going on?

**Comment by lfittl** [comment]
@avinoamr I wonder if thats due to the parser currently being 9.5 still - is that syntax that got added in 9.6 by any chance?

**Comment by avinoamr** [comment]
1. The ROWS syntax was added in [9.4](https://www.postgresql.org/docs/9.4/static/sql-select.html). Maybe I'm reading it wrong?
2. I believe that their documentation is out-dated, as all of the relevant fields are found in `RangeFunction.Alias` and `RangeFunction.Coldeflist`.

**Comment by lfittl** [comment]
@avinoamr Ah, got it - yeah, I blame Postgres on that one ;)
