### ISSUE TITLE
"Ruby is more feature complete"

### ISSUE THREAD

**Issue by tejasmanohar** [lfittl/pg_query_go#8]
>Note that the original Ruby version of this library is much more feature complete.

Which features are missing from the Go library? Anything but deparse?

**Comment by lfittl** [comment]
@tejasmanohar Deparsing, table extraction logic (https://github.com/lfittl/pg_query/blob/master/lib/pg_query/parse.rb#L65) and smart truncation (https://github.com/lfittl/pg_query/blob/master/lib/pg_query/truncate.rb)

Patches welcome of course - I'll probably be working on some of these in the next couple of months.

Do you have a particular use case that you are looking to use this library for?

**Comment by tejasmanohar** [comment]
@lfittl I was (and I guess, am) considering building a side project to auto-optimize some annoying things in PostgreSQL, e.g. wCTEs -> subqueries to avoid optimization fences.

**Comment by tejasmanohar** [comment]
I may hack on deparsing on the side. PS: Just realized you're from Citus. That's sick!

**Comment by lfittl** [comment]
@tejasmanohar Nice, that sounds like a fun side-project - let me know how it goes :)
