### ISSUE TITLE
how can i know the meaning of the json key?

### ISSUE THREAD

**Issue by weiboyiyou** [lfittl/pg_query_go#9]
Hi,lfittl:
    how can i know the meaning of the json key?
    like this:What's the meaning of the key "inh"?
    [
    {
        "RawStmt": {
            "stmt": {
                "DeleteStmt": {
                    "relation": {
                        "RangeVar": {
                            "relname": "a",
                            "inh": true,
                            "relpersistence": "p",
                            "location": 12
                        }
                    },
                    "whereClause": {
                        "BoolExpr": {
                            "boolop": 1,
                            "args": [
                                {
                                    "A_Expr": {
                                        "kind": 0,
                                        "name": [
                                            {
                                                "String": {
                                                    "str": "="
                                                }
                                            }
                                        ],
                                        "lexpr": {
                                            "A_Const": {
                                                "val": {
                                                    "Integer": {
                                                        "ival": 1
                                                    }
                                                },
                                                "location": 20
                                            }
                                        },
                                        "rexpr": {
                                            "A_Const": {
                                                "val": {
                                                    "Integer": {
                                                        "ival": 1
                                                    }
                                                },
                                                "location": 22
                                            }
                                        },
                                        "location": 21
                                    }
                                },
                                {
                                    "A_Expr": {
                                        "kind": 0,
                                        "name": [
                                            {
                                                "String": {
                                                    "str": "="
                                                }
                                            }
                                        ],
                                        "lexpr": {
                                            "ColumnRef": {
                                                "fields": [
                                                    {
                                                        "String": {
                                                            "str": "a"
                                                        }
                                                    }
                                                ],
                                                "location": 27
                                            }
                                        },
                                        "rexpr": {
                                            "A_Const": {
                                                "val": {
                                                    "Integer": {
                                                        "ival": 1
                                                    }
                                                },
                                                "location": 29
                                            }
                                        },
                                        "location": 28
                                    }
                                }
                            ],
                            "location": 24
                        }
                    }
                }
            },
            "stmt_len": 30
        }
    }
]

**Comment by lfittl** [comment]
Hi @weiboyiyou - thanks for reaching out!

You can usually find more details on what a certain field means by looking at the PostgreSQL source code - in this case the [source for the RangeVar struct](https://github.com/postgres/postgres/blob/master/src/include/nodes/primnodes.h#L63):

```
typedef struct RangeVar
{
	NodeTag		type;
	char	   *catalogname;	/* the catalog (database) name, or NULL */
	char	   *schemaname;		/* the schema name, or NULL */
	char	   *relname;		/* the relation/sequence name */
	bool		inh;			/* expand rel by inheritance? recursively act
								 * on children? */
	char		relpersistence; /* see RELPERSISTENCE_* in pg_class.h */
	Alias	   *alias;			/* table alias & optional column aliases */
	int			location;		/* token location, or -1 if unknown */
} RangeVar;
```

And to explain in a bit more detail - the `inh` setting reflects whether you specify the `ONLY` keyword on a query (false means `ONLY` was specified, the default is true, i.e. not specified). That keyword determines whether the query affects **only** the table itself or all **inh**eriting tables as well.

Hope that helps!

**Comment by weiboyiyou** [comment]
Hi，
   Thank you very much!
